export const openApiSpec = {
  openapi: '3.0.3',
  info: {
    title: 'Aora Business Email API',
    version: '1.0.0',
    description: 'Orchestration layer abstracting MXroute, Cloudflare and Paystack. All provider credentials stay server-side.',
  },
  servers: [{ url: 'http://localhost:4000/api/v1', description: 'Local' }, { url: 'https://api.aora.ng/api/v1', description: 'Production' }],
  components: {
    securitySchemes: {
      cookieAuth: { type: 'apiKey', in: 'cookie', name: 'aora_session', description: 'Secure httpOnly cookie' },
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
    },
    schemas: {
      Error: { type: 'object', properties: { error: { type: 'object', properties: { code: { type: 'string', example: 'DOMAIN_NOT_VERIFIED' }, message: { type: 'string' }, fieldErrors: { type: 'object', additionalProperties: { type: 'string' } } } }, meta: { type: 'object' } } },
      Pagination: { type: 'object', properties: { page: { type: 'integer' }, limit: { type: 'integer' }, total: { type: 'integer' }, totalPages: { type: 'integer' } } },
      Plan: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, slug: { type: 'string', enum: ['starter', 'business', 'pro'] }, annualPrice: { type: 'integer' }, maxMailboxes: { type: 'integer' } } },
      Domain: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, status: { type: 'string', enum: ['pending', 'provisioning', 'dns_pending', 'verifying', 'verified', 'active', 'error', 'suspended'] }, verifiedAt: { type: 'string', format: 'date-time' } } },
      Mailbox: { type: 'object', properties: { id: { type: 'string' }, email: { type: 'string' }, quotaBytes: { type: 'integer' }, usedBytes: { type: 'integer' }, status: { type: 'string', enum: ['pending', 'active', 'suspended', 'error'] } } },
    },
  },
  security: [{ cookieAuth: [] }, { bearerAuth: [] }],
  paths: {
    '/auth/register': { post: { summary: 'Register', tags: ['Auth'], security: [], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name', 'businessName', 'email', 'password', 'acceptTerms'], properties: { name: { type: 'string' }, businessName: { type: 'string' }, email: { type: 'string', format: 'email' }, password: { type: 'string' }, acceptTerms: { type: 'boolean' } } } } }, responses: { '201': { description: 'Created' }, '409': { description: 'Email taken' } } } },
    '/auth/login': { post: { summary: 'Login', tags: ['Auth'], security: [], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { email: { type: 'string' }, password: { type: 'string' } } } } }, responses: { '200': { description: 'OK' }, '401': { description: 'Invalid credentials' } } } },
    '/auth/logout': { post: { summary: 'Logout', tags: ['Auth'], responses: { '200': { description: 'OK' } } } },
    '/auth/session': { get: { summary: 'Get session', tags: ['Auth'], responses: { '200': { description: 'OK' } } } },
    '/plans': { get: { summary: 'List plans', tags: ['Plans'], security: [], responses: { '200': { description: 'OK' } } } },
    '/domains': {
      get: { summary: 'List domains', tags: ['Domains'], parameters: [{ name: 'page', in: 'query', schema: { type: 'integer' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }], responses: { '200': { description: 'Paginated' } } },
      post: { summary: 'Create domain', tags: ['Domains'], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { name: { type: 'string' } } } } }, responses: { '201': { description: 'Created' } } },
    },
    '/domains/{id}': { get: { summary: 'Get domain', tags: ['Domains'], parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'OK' } } }, delete: { summary: 'Delete domain', tags: ['Domains'], responses: { '200': { description: 'Deleted' } } } },
    '/domains/{id}/verify': { post: { summary: 'Verify domain DNS', tags: ['Domains'], responses: { '200': { description: 'Verified' } } } },
    '/domains/{id}/dns': { get: { summary: 'Get DNS records', tags: ['DNS'], responses: { '200': { description: 'OK' } } } },
    '/mailboxes': {
      get: { summary: 'List mailboxes', tags: ['Mailboxes'], parameters: [{ name: 'page', in: 'query', schema: { type: 'integer' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }], responses: { '200': { description: 'OK' } } },
      post: { summary: 'Create mailbox', tags: ['Mailboxes'], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { domainId: { type: 'string' }, localPart: { type: 'string' }, password: { type: 'string' } } } } }, responses: { '201': { description: 'Created' } } },
    },
    '/mailboxes/{id}': { get: { summary: 'Get mailbox', tags: ['Mailboxes'] }, patch: { summary: 'Update mailbox quota', tags: ['Mailboxes'] }, delete: { summary: 'Delete mailbox', tags: ['Mailboxes'] } },
    '/mailboxes/{id}/suspend': { post: { summary: 'Suspend mailbox', tags: ['Mailboxes'] } },
    '/mailboxes/{id}/unsuspend': { post: { summary: 'Unsuspend mailbox', tags: ['Mailboxes'] } },
    '/forwarders': { get: { summary: 'List forwarders', tags: ['Forwarders'] }, post: { summary: 'Create forwarder', tags: ['Forwarders'] } },
    '/subscriptions': { get: { summary: 'Get subscription', tags: ['Subscriptions'] }, post: { summary: 'Select plan', tags: ['Subscriptions'], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { planId: { type: 'string' } } } } } } },
    '/payments': { get: { summary: 'List payments', tags: ['Payments'] }, post: { summary: 'Create checkout', tags: ['Payments'] } },
    '/payments/checkout': { post: { summary: 'Create Paystack checkout', tags: ['Payments'] } },
    '/invoices': { get: { summary: 'List invoices', tags: ['Invoices'] } },
    '/usage': { get: { summary: 'Get usage', tags: ['Usage'] }, post: { summary: 'Sync usage', tags: ['Usage'] } },
    '/support': { get: { summary: 'List support tickets', tags: ['Support'] }, post: { summary: 'Create support ticket', tags: ['Support'] } },
    '/webhooks/paystack': { post: { summary: 'Paystack webhook', tags: ['Webhooks'], security: [], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { event: { type: 'string' }, data: { type: 'object' } } } } }, responses: { '200': { description: 'Idempotent OK' } } } },
    '/admin/metrics': { get: { summary: 'Admin metrics', tags: ['Admin'] } },
    '/admin/organizations': { get: { summary: 'Admin list organizations', tags: ['Admin'] } },
    '/health': { get: { summary: 'Health', tags: ['Health'], security: [] } },
    '/health/ready': { get: { summary: 'Readiness', tags: ['Health'], security: [] } },
  },
} as const;
